using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Statee.Generator;

/// <summary>
/// [StateeState] を付与した partial class に IStateProvider 実装を生成する
/// incremental generator(docs/MEMO.md D-022)。
/// スナップショットは [StateeField] を付与したプロパティ・フィールドの現在値を持つ匿名型。
/// </summary>
[Generator]
public sealed class StateProviderGenerator : IIncrementalGenerator
{
    private const string StateAttributeName = "Statee.Core.StateeStateAttribute";
    private const string FieldAttributeName = "Statee.Core.StateeFieldAttribute";

    private static readonly DiagnosticDescriptor RequirePartial = new(
        id: "STATEE001",
        title: "[StateeState] を付与するクラスは partial にする",
        messageFormat: "[StateeState] を付与したクラス '{0}' に partial 修飾子が無いため、IStateProvider 実装を生成できない",
        category: "Statee.Generator",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var providers = context.SyntaxProvider.ForAttributeWithMetadataName(
            StateAttributeName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => CreateModel(ctx)
        );

        context.RegisterSourceOutput(providers, static (spc, model) => Emit(spc, model));
    }

    private sealed record ProviderModel(
        string? Namespace,
        string ClassName,
        string Path,
        bool IsPartial,
        string MemberNames,
        Location Location
    );

    private static ProviderModel CreateModel(GeneratorAttributeSyntaxContext context)
    {
        var symbol = (INamedTypeSymbol)context.TargetSymbol;
        var syntax = (ClassDeclarationSyntax)context.TargetNode;
        var path = context.Attributes[0].ConstructorArguments[0].Value as string ?? string.Empty;
        var memberNames = new StringBuilder();
        foreach (var member in symbol.GetMembers())
        {
            var isCapturable =
                member
                is IPropertySymbol { GetMethod: not null }
                    or IFieldSymbol { IsImplicitlyDeclared: false };
            if (!isCapturable || !HasFieldAttribute(member))
            {
                continue;
            }

            if (memberNames.Length > 0)
            {
                memberNames.Append(',');
            }

            memberNames.Append(member.Name);
        }

        return new ProviderModel(
            Namespace: symbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : symbol.ContainingNamespace.ToDisplayString(),
            ClassName: symbol.Name,
            Path: path,
            IsPartial: syntax.Modifiers.Any(SyntaxKind.PartialKeyword),
            MemberNames: memberNames.ToString(),
            Location: syntax.Identifier.GetLocation()
        );
    }

    private static bool HasFieldAttribute(ISymbol member)
    {
        foreach (var attribute in member.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() == FieldAttributeName)
            {
                return true;
            }
        }

        return false;
    }

    private static void Emit(SourceProductionContext context, ProviderModel model)
    {
        if (!model.IsPartial)
        {
            context.ReportDiagnostic(
                Diagnostic.Create(RequirePartial, model.Location, model.ClassName)
            );
            return;
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        var indent = string.Empty;
        if (model.Namespace is not null)
        {
            builder.AppendLine($"namespace {model.Namespace}");
            builder.AppendLine("{");
            indent = "    ";
        }

        builder.AppendLine(
            $"{indent}partial class {model.ClassName} : global::Statee.Core.IStateProvider"
        );
        builder.AppendLine($"{indent}{{");
        builder.AppendLine(
            $"{indent}    public string Path => {SymbolDisplay.FormatLiteral(model.Path, quote: true)};"
        );
        builder.AppendLine();
        builder.AppendLine($"{indent}    public object CaptureState() =>");
        builder.AppendLine($"{indent}        new");
        builder.AppendLine($"{indent}        {{");
        foreach (var name in SplitMemberNames(model.MemberNames))
        {
            builder.AppendLine($"{indent}            {name} = this.{name},");
        }

        builder.AppendLine($"{indent}        }};");
        builder.AppendLine($"{indent}}}");
        if (model.Namespace is not null)
        {
            builder.AppendLine("}");
        }

        var hintName = model.Namespace is null
            ? $"{model.ClassName}.StateProvider.g.cs"
            : $"{model.Namespace}.{model.ClassName}.StateProvider.g.cs";
        context.AddSource(hintName, SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static string[] SplitMemberNames(string memberNames) =>
        memberNames.Length == 0 ? [] : memberNames.Split(',');
}
